In [1]:
# combining Costs file with Markets
# note that we will merge on the efficient measure name and the market at that is what 
# defines a measure (which is how we did the avoided costs (at the measure level)). However the market and 
# adoption model are at the condition level so after the merge we will have a lot of NAs 
# all the existing and baseline equipment will have NAs
# we will need to make sure they get pulled into the adoption model correctly
# the flags will need to force this
# this step is needed to get all the information the adoption model needs in one dataframe

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
df = pd.read_pickle("020_input/measure_costs_benefits.plk")
#line added but need to check with config file
df['building_type'] = df['building_type'].replace({'multi_family': 'multifamily', 'multi_family_li': 'multifamily_li'})
df

,measure_name,sector,program,market,electric_utility,gas_utility,baseline_condition,efficient_condition,complementary_condition,building_type,...,TRC_BCR,SCT_cost,SCT_benefit,SCT_BCR,RIM_cost,RIM_benefit,RIM_BCR,PCT_cost,PCT_benefit,PCT_BCR
0,furnace_oil_existing_residential_to_furnace_oi...,residential,NLIRNC,Ret_ER,test_utility_1,test_utility_1,furnace_oil_existing_residential,furnace_oil_efficient_residential,NaN,multifamily,...,4.801938,1680.0,8163.390134,4.859161,1238.612470,8611.980582,6.952926,700,9221.848958,13.174070
1,furnace_oil_existing_residential_to_furnace_oi...,residential,LIRNC,Ret_ER,test_utility_1,test_utility_1,furnace_oil_existing_residential,furnace_oil_efficient_residential,NaN,multifamily_li,...,4.801938,1680.0,8163.390134,4.859161,1238.612470,8611.980582,6.952926,700,9221.848958,13.174070
2,furnace_oil_existing_residential_to_furnace_oi...,residential,NLIRNC,Ret_ER,test_utility_1,test_utility_1,furnace_oil_existing_residential,furnace_oil_efficient_residential,NaN,single_family,...,2.139246,1680.0,3636.660007,2.164679,1172.716654,4138.658036,3.529120,700,4682.630596,6.689472
3,furnace_oil_existing_residential_to_furnace_oi...,residential,LIRNC,Ret_ER,test_utility_1,test_utility_1,furnace_oil_existing_residential,furnace_oil_efficient_residential,NaN,single_family_li,...,2.139246,1680.0,3636.660007,2.164679,1172.716654,4138.658036,3.529120,700,4682.630596,6.689472
4,furnace_oil_baseline_residential_to_furnace_oi...,residential,NLIRNC,NC,test_utility_1,test_utility_1,furnace_oil_baseline_residential,furnace_oil_efficient_residential,NaN,multifamily,...,4.801938,1680.0,8163.390134,4.859161,1238.612470,8611.980582,6.952926,700,9221.848958,13.174070
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,refrigerator_electricity_top10_residential_ref...,residential,LIRROB,ROB,test_utility_1,none,refrigerator_electricity_baseline_residential,refrigerator_electricity_top10_residential,NaN,single_family_li,...,1.089479,1800.0,2958.004063,1.643336,2430.055249,2544.786640,1.047213,750,4301.097795,5.734797
188,refrigerator_electricity_top10_residential_ref...,residential,NLIRRENO,RENO,test_utility_1,none,refrigerator_electricity_baseline_residential,refrigerator_electricity_top10_residential,NaN,multifamily,...,1.809771,1800.0,4919.156168,2.732865,3250.092082,3841.311067,1.181908,750,6417.659055,8.556879
189,refrigerator_electricity_top10_residential_ref...,residential,LIRRENO,RENO,test_utility_1,none,refrigerator_electricity_baseline_residential,refrigerator_electricity_top10_residential,NaN,multifamily_li,...,1.809771,1800.0,4919.156168,2.732865,3250.092082,3841.311067,1.181908,750,6417.659055,8.556879
190,refrigerator_electricity_top10_residential_ref...,residential,NLIRRENO,RENO,test_utility_1,none,refrigerator_electricity_baseline_residential,refrigerator_electricity_top10_residential,NaN,single_family,...,1.089479,1800.0,2958.004063,1.643336,2430.055249,2544.786640,1.047213,750,4301.097795,5.734797
191,refrigerator_electricity_top10_residential_ref...,residential,LIRRENO,RENO,test_utility_1,none,refrigerator_electricity_baseline_residential,refrigerator_electricity_top10_residential,NaN,single_family_li,...,1.089479,1800.0,2958.004063,1.643336,2430.055249,2544.786640,1.047213,750,4301.097795,5.734797

In [4]:
### making a tool###
# # make a list from df which is efficient_condition and measure_life_(yrs) and drop duplicates

#this will have to come from the workpapers 
df_eff_life = df[['efficient_condition', 'measure_life_(yrs)']].drop_duplicates()
df_base_life = df[['baseline_condition', 'measure_life_(yrs)']].drop_duplicates()
# now just stack these two dataframes on top of each other with the columns efficient_condition and baseline_condition renamed to condition
df_eff_life = df_eff_life.rename(columns={'efficient_condition': 'condition', 'measure_life_(yrs)': 'measure_life_(yrs)'})
df_base_life = df_base_life.rename(columns={'baseline_condition': 'condition', 'measure_life_(yrs)': 'measure_life_(yrs)'})

df_life = pd.concat([df_eff_life, df_base_life]).drop_duplicates().reset_index(drop=True)
df_life

                                        condition  measure_life_(yrs)
0               furnace_oil_efficient_residential                  10
1       furnace_natural_gas_efficient_residential                  10
2  refrigerator_electricity_efficient_residential                  10
3      refrigerator_electricity_top10_residential                  10
4                furnace_oil_existing_residential                  10
5                furnace_oil_baseline_residential                  10
6        furnace_natural_gas_existing_residential                  10
7        furnace_natural_gas_baseline_residential                  10
8   refrigerator_electricity_existing_residential                  10
9   refrigerator_electricity_baseline_residential                  10

In [5]:
df_yr1 = pd.read_pickle("020_input/df_yr1_001.pkl")
# Apply filters
# df_yr1 = df_yr1[
#     (df_yr1['electric_utility'] == 'test_utility_1') &
#     (df_yr1['gas_utility'] == 'test_utility_1') &
#     (df_yr1['competition_group'] == 'refrigeration')
# ]
# df_yr1

In [6]:
df_yr1 = pd.read_pickle("020_input/df_yr1_001.pkl")
# first need to change df_yr1 into long format with the current column names which are building types into rows and a new column for building type
df_yr1 = df_yr1.melt(id_vars=['condition', 'competition_group', 'subgroup', 'electric_utility', 'gas_utility'], var_name='building_type', value_name='initial_count')

df_yr1

,condition,competition_group,subgroup,electric_utility,gas_utility,building_type,initial_count
0,furnace_oil_efficient_residential,heating_cooling,oil_furnace,test_utility_1,test_utility_1,single_family_year_one,5000.0
1,furnace_oil_efficient_residential,heating_cooling,oil_furnace,test_utility_1,test_utility_2,single_family_year_one,10000.0
2,furnace_oil_efficient_residential,heating_cooling,oil_furnace,test_utility_1,none,single_family_year_one,27500.0
3,furnace_oil_baseline_residential,heating_cooling,oil_furnace,test_utility_1,test_utility_1,single_family_year_one,2500.0
4,furnace_oil_baseline_residential,heating_cooling,oil_furnace,test_utility_1,test_utility_2,single_family_year_one,5000.0
...,...,...,...,...,...,...,...
115,refrigerator_electricity_top10_residential,refrigeration,full_size,test_utility_1,test_utility_2,multifamily_li_year_one,3000.0
116,refrigerator_electricity_top10_residential,refrigeration,full_size,test_utility_1,none,multifamily_li_year_one,2100.0
117,refrigerator_electricity_existing_residential,refrigeration,full_size,test_utility_1,test_utility_1,multifamily_li_year_one,600.0
118,refrigerator_electricity_existing_residential,refrigeration,full_size,test_utility_1,test_utility_2,multifamily_li_year_one,2400.0
119,refrigerator_electricity_existing_residential,refrigeration,full_size,test_utility_1,none,multifamily_li_year_one,1680.0

In [7]:
# use df_life to map measure life to df_yr1 based on efficient_condition
df_yr1 = pd.merge(df_yr1, df_life, left_on='condition', right_on='condition', how='left')
df_yr1

,condition,competition_group,subgroup,electric_utility,gas_utility,building_type,initial_count,measure_life_(yrs)
0,furnace_oil_efficient_residential,heating_cooling,oil_furnace,test_utility_1,test_utility_1,single_family_year_one,5000.0,10
1,furnace_oil_efficient_residential,heating_cooling,oil_furnace,test_utility_1,test_utility_2,single_family_year_one,10000.0,10
2,furnace_oil_efficient_residential,heating_cooling,oil_furnace,test_utility_1,none,single_family_year_one,27500.0,10
3,furnace_oil_baseline_residential,heating_cooling,oil_furnace,test_utility_1,test_utility_1,single_family_year_one,2500.0,10
4,furnace_oil_baseline_residential,heating_cooling,oil_furnace,test_utility_1,test_utility_2,single_family_year_one,5000.0,10
...,...,...,...,...,...,...,...,...
115,refrigerator_electricity_top10_residential,refrigeration,full_size,test_utility_1,test_utility_2,multifamily_li_year_one,3000.0,10
116,refrigerator_electricity_top10_residential,refrigeration,full_size,test_utility_1,none,multifamily_li_year_one,2100.0,10
117,refrigerator_electricity_existing_residential,refrigeration,full_size,test_utility_1,test_utility_1,multifamily_li_year_one,600.0,10
118,refrigerator_electricity_existing_residential,refrigeration,full_size,test_utility_1,test_utility_2,multifamily_li_year_one,2400.0,10
119,refrigerator_electricity_existing_residential,refrigeration,full_size,test_utility_1,none,multifamily_li_year_one,1680.0,10

In [8]:

# now I am going to allocate the initial counts into the markets based on the stock and flow proportions from expert opinion
# there are three markets that I want to allocate into: RET_ER, REMAINING, and ROB 
# ROB is 1/EUL (measure_life (yrs)
# RET_ER is 1/3 of non ROB stock
# remaining is 2/3 of non ROB stock
df_yr1['ROB'] = df_yr1['initial_count'] / df_yr1['measure_life_(yrs)']  # assuming measure life of 15 years
####################################
######### Feature add ##############
####################################
# We need to also include Ret_add_on
# the adoption model is ready for this
#df_yr1['RET_ADD_ON'] = (df_yr1['initial_count'] - df_yr1['ROB']) 
# RET_ADD_ON is all of the non ROB stock



df_yr1['RET_ER'] = (df_yr1['initial_count'] - df_yr1['ROB']) * (1/3)
df_yr1['REMAINING'] = (df_yr1['initial_count'] - df_yr1['ROB']) * (2/3)

df_yr1 = df_yr1.melt(id_vars=['condition', 'competition_group', 'subgroup', 'electric_utility', 'gas_utility', 'building_type', 'measure_life_(yrs)', 'initial_count'], var_name='market', value_name='count')
#need to remove the text '_year_one' from the building_type column
df_yr1['building_type'] = df_yr1['building_type'].str.replace('_year_one', '')

In [9]:
# we need to add a check to make sure the Market Characterization sheet and the work papers have the same conditions in them
# we also need to add a check to make sure all existing and baseline versions are included as needed
# for now remove all nas on measure_life_(yrs)
#causeing error
df_yr1 = df_yr1.dropna(subset=['measure_life_(yrs)'])
df_yr1

,condition,competition_group,subgroup,electric_utility,gas_utility,building_type,measure_life_(yrs),initial_count,market,count
0,furnace_oil_efficient_residential,heating_cooling,oil_furnace,test_utility_1,test_utility_1,single_family,10,5000.0,ROB,500.0
1,furnace_oil_efficient_residential,heating_cooling,oil_furnace,test_utility_1,test_utility_2,single_family,10,10000.0,ROB,1000.0
2,furnace_oil_efficient_residential,heating_cooling,oil_furnace,test_utility_1,none,single_family,10,27500.0,ROB,2750.0
3,furnace_oil_baseline_residential,heating_cooling,oil_furnace,test_utility_1,test_utility_1,single_family,10,2500.0,ROB,250.0
4,furnace_oil_baseline_residential,heating_cooling,oil_furnace,test_utility_1,test_utility_2,single_family,10,5000.0,ROB,500.0
...,...,...,...,...,...,...,...,...,...,...
355,refrigerator_electricity_top10_residential,refrigeration,full_size,test_utility_1,test_utility_2,multifamily_li,10,3000.0,REMAINING,1800.0
356,refrigerator_electricity_top10_residential,refrigeration,full_size,test_utility_1,none,multifamily_li,10,2100.0,REMAINING,1260.0
357,refrigerator_electricity_existing_residential,refrigeration,full_size,test_utility_1,test_utility_1,multifamily_li,10,600.0,REMAINING,360.0
358,refrigerator_electricity_existing_residential,refrigeration,full_size,test_utility_1,test_utility_2,multifamily_li,10,2400.0,REMAINING,1440.0
359,refrigerator_electricity_existing_residential,refrigeration,full_size,test_utility_1,none,multifamily_li,10,1680.0,REMAINING,1008.0

In [10]:
# now we just merge df_yr1 and df on condition_name, competition_group, electric_utility, gas_utility, building_type, and market
df_yrs = pd.merge(df_yr1, df, left_on=['condition', 'electric_utility', 'gas_utility', 'building_type', 'market', 'measure_life_(yrs)'], right_on=['efficient_condition',  'electric_utility', 'gas_utility', 'building_type', 'market', 'measure_life_(yrs)'], how='left')
df_yrs 

########## Issue only electric utility 1 pulling through ###########

,condition,competition_group,subgroup,electric_utility,gas_utility,building_type,measure_life_(yrs),initial_count,market,count,...,TRC_BCR,SCT_cost,SCT_benefit,SCT_BCR,RIM_cost,RIM_benefit,RIM_BCR,PCT_cost,PCT_benefit,PCT_BCR
0,furnace_oil_efficient_residential,heating_cooling,oil_furnace,test_utility_1,test_utility_1,single_family,10,5000.0,ROB,500.0,...,2.139246,1680.0,3636.660007,2.164679,1172.716654,4138.658036,3.52912,700.0,4682.630596,6.689472
1,furnace_oil_efficient_residential,heating_cooling,oil_furnace,test_utility_1,test_utility_2,single_family,10,10000.0,ROB,1000.0,...,2.144324,1680.0,3645.190210,2.169756,1172.716654,4138.658036,3.52912,700.0,4691.160799,6.701658
2,furnace_oil_efficient_residential,heating_cooling,oil_furnace,test_utility_1,none,single_family,10,27500.0,ROB,2750.0,...,2.139246,1680.0,3636.660007,2.164679,1172.716654,4138.658036,3.52912,700.0,4682.630596,6.689472
3,furnace_oil_baseline_residential,heating_cooling,oil_furnace,test_utility_1,test_utility_1,single_family,10,2500.0,ROB,250.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,furnace_oil_baseline_residential,heating_cooling,oil_furnace,test_utility_1,test_utility_2,single_family,10,5000.0,ROB,500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,refrigerator_electricity_top10_residential,refrigeration,full_size,test_utility_1,test_utility_2,multifamily_li,10,3000.0,REMAINING,1800.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356,refrigerator_electricity_top10_residential,refrigeration,full_size,test_utility_1,none,multifamily_li,10,2100.0,REMAINING,1260.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
357,refrigerator_electricity_existing_residential,refrigeration,full_size,test_utility_1,test_utility_1,multifamily_li,10,600.0,REMAINING,360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
358,refrigerator_electricity_existing_residential,refrigeration,full_size,test_utility_1,test_utility_2,multifamily_li,10,2400.0,REMAINING,1440.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
359,refrigerator_electricity_existing_residential,refrigeration,full_size,test_utility_1,none,multifamily_li,10,1680.0,REMAINING,1008.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#Not removing NAs we need to make sure all the files have the shared column names and such

df_yrs.to_pickle("./020_output/df_yrs.pkl")
df_yrs.to_pickle("./030_input/df_yrs.pkl")
df_yrs.to_csv("./020_output/df_yrs.csv")
df_yrs.to_csv("./030_input/df_yrs.csv")